lib LibXm
  $xmArrowButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmArrowButtonGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmBulletinBoardWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmCascadeButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmCascadeButtonGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmClipWindowWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmColorObjClass : X11::Xt::X_WidgetClassRec*
  $xmComboBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmCommandWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDesktopClass : X11::Xt::X_WidgetClassRec*
  $xmDialogShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDialogShellExtObjectClass : X11::Xt::X_WidgetClassRec*
  $xmDragContextClass : X11::Xt::X_WidgetClassRec*
  $xmDragIconObjectClass : X11::Xt::X_WidgetClassRec*
  $xmDragOverShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDrawingAreaWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDrawnButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDropDownWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmDropSiteManagerObjectClass : X11::Xt::X_WidgetClassRec*
  $xmDropTransferObjectClass : X11::Xt::X_WidgetClassRec*
  $xmExt18ListWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmExtObjectClass : X11::Xt::X_WidgetClassRec*
  $xmFileSelectionBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmFormWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmFrameWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmGrabShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmLabelWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmLabelGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmListWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmMainWindowWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmManagerWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmMenuShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmMessageBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmMultiListWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmNotebookWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmPanedWindowWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmPrimitiveWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmPrintShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmProtocolObjectClass : X11::Xt::X_WidgetClassRec*
  $xmPushButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmPushButtonGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmRowColumnWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmSimpleSpinBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmSashWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmScaleWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmScrollBarWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmScrolledWindowWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmSelectionBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmSeparatorGadgetClass : X11::Xt::X_WidgetClassRec*
  $xmSeparatorWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmShellExtObjectClass : X11::Xt::X_WidgetClassRec*
  $xmSpinBoxWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmTearOffButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmTextWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmTextFieldWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmToggleButtonWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmToggleButtonGadgetClass : X11::Xt::X_WidgetClassRec*
  $vendorShellWidgetClass : X11::Xt::X_WidgetClassRec*
  $xmVendorShellExtObjectClass : X11::Xt::X_WidgetClassRec*
end
